doc/install.rst

The link to the tutorial was added to doc/install.rst.

Adding a link to the installation tutorial on YouTube

---

autode/calculation.py
autode/smiles/smiles.py
autode/smiles/smiles_parser.py
tests/test_smiles_parser.py
tests/test_xtb_calc.py

Fixes issue in SMILES parser where the charge was additive with sequential parse_smiles calls, so switch to top-level parse_smiles function

SMILES parser fix

---

README.md
autode/__init__.py
autode/bond_lengths.py
autode/conformers/conf_gen.py
autode/conformers/conformer.py
autode/smiles/smiles.py
autode/species/complex.py
autode/species/molecule.py
autode/species/species.py
autode/transition_states/base.py
autode/transition_states/locate_tss.py
autode/transition_states/transition_state.py
autode/transition_states/truncation.py
doc/common/rmsd.py
tests/test_bond_assignment.py
tests/test_conf_gen.py
tests/test_molecule.py
tests/test_nwchem.py
tests/test_species.py
tests/test_substitution.py
tests/test_ts_template.py

Much more reasonable bond length estimations for pairs not in the bond-length dict
Add n_atoms as a property, so the atoms setter (species.set_atoms) can be removed

Remove set_atoms

---

examples/addition_elimination.py
examples/carbonyl_addition.py

Fix for incorrect assignment of basis set in example

Example correction

---

autode/smiles/builder.py
tests/test_smiles_builder.py

Slight modification to the repulsion parameters in the 3D build, such that multiply fused rings minimise to reasonable structures

Parameter tweak

---

autode/smiles/parser.py
tests/test_smiles_parser.py

Fixes connectivity for parser with SMILES with X(...)1 type branching

Apply ring closure to non-branched atom

---

autode/__init__.py
autode/transition_states/locate_tss.py
setup.py
tests/test_locate_tss.py
tests/test_smiles_builder.py

Improved errors

---

autode/__init__.py
autode/smiles/angles.py
autode/smiles/base.py
autode/smiles/builder.py
autode/smiles/parser.py
autode/transition_states/locate_tss.py
doc/reference/smiles/builder.rst
doc/reference/smiles/index.rst
doc/reference/smiles/parser.rst
setup.py
tests/test_locate_tss.py
tests/test_molecule.py
tests/test_smiles_base.py
tests/test_smiles_builder.py
tests/test_smiles_parser.py

- Fixes #53
- Adds correct atom types for sp2 group 15 elements

Enable more than 9 rings in a structure

---

autode/smiles/smiles.py
autode/wrappers/XTB.py
tests/test_molecule.py

Fixes #62  and #63. Thanks to Carl Mensch for spotting these!

Spin bugfix

---

autode/conformers/conformers.py
tests/test_conformers.py

Removes possible divide by zero in conformer calculations (#73)

Conformer calculation edge case

---

autode/conformers/conformers.py
autode/species/complex.py
doc/common/water_trimer.py
tests/test_conformers.py

Fixes #76, and improves example slightly.

Fixes incorrect filename for NCI conformers

---

autode/config.py
autode/plotting.py
autode/species/species.py
autode/thermochemistry/igm.py
autode/units.py
autode/values.py
autode/wrappers/G09.py
autode/wrappers/NWChem.py
autode/wrappers/ORCA.py
doc/changelog.rst
tests/test_config.py
tests/test_species.py
tests/test_value.py

~Change reactant_to_product -> .to_product()~
Will break backwards compatibility, so best to change in v.1.2

Improve usability

---

autode/reactions/reaction_types.py
tests/test_reactions.py

Improves the classification of reactions by throwing more interpretable exceptions. Also adds correct equality testing and improves docstrings
***

Improve reaction classify

---

autode/values.py
tests/test_value.py
tests/test_values.py

Adds more tests, satisfying codecov and me, to a lesser extent 😛

Adds additional tests

---

autode/neb/idpp.py
autode/neb/original.py
doc/changelog.rst
doc/examples/tss.rst
doc/reference/index.rst
doc/reference/neb/ci.rst
doc/reference/neb/idpp.rst
doc/reference/neb/index.rst
doc/reference/neb/neb.rst
doc/reference/neb/original.rst
tests/test_neb.py

Fixes #103 by implementing the image dependent pair potential from https://arxiv.org/pdf/1406.1512.pdf
***

IDPP for NEB

---

autode/wrappers/G09.py
doc/changelog.rst

Fixes Hessian extraction from calculations where a "Input orientation" block is not printed in the output file, which seems to be possible for some Gaussian 09 calculations.

Gaussian wrapper bugfix 🐞 

---

autode/utils.py
tests/test_utils.py

Adds tests are removed unused `NoDeamonProcess`

Improve unit test coverage

---

autode/__init__.py
autode/reactions/reaction.py
doc/changelog.rst
setup.py
tests/test_reaction_class.py

Fix clashing names of formula only molecules in a reaction

---

autode/conformers/conformer.py
doc/install.rst

- Adds a link to what to do if conda solve fails (highlighted in #148 )
- Fixes LGTM alterts

Adds documentation

---

autode/hessians.py

Rotate projection vectors from principal axis

---

autode/calculation.py
autode/config.py
autode/hessians.py
autode/wrappers/ORCA.py
autode/wrappers/functionals.py
autode/wrappers/keywords.py
doc/changelog.rst
doc/examples/thermochem.rst
tests/test_config.py
tests/test_hessian.py
tests/test_keywords.py
tests/test_orca_calc.py

Add frequency scaling

---

autode/calculation.py
autode/config.py
autode/mol_graphs.py
autode/path/adaptive.py
autode/solvent/solvents.py
autode/transition_states/transition_state.py
autode/transition_states/ts_guess.py
autode/utils.py
autode/wrappers/ORCA.py
autode/wrappers/keywords.py
doc/changelog.rst
doc/common/XY_bde_XTB.py
doc/config.rst
tests/test_calculation.py
tests/test_gaussian_calc.py
tests/test_graphs.py
tests/test_keywords.py
tests/test_mopac_calc.py
tests/test_nwchem.py
tests/test_orca_calc.py
tests/test_path.py
tests/test_qchem.py
tests/test_xtb_calc.py

Refactors the calculation and graph classes, along with minor parts of others. This PR should not have any functional changes to the code..

Refactoring

---

.github/workflows/catch.yml
.github/workflows/pytest.yml
.github/workflows/pytest_cov.yml
autode/transition_states/base.py
autode/transition_states/transition_state.py
doc/changelog.rst
tests/test_ts.py

Allow defining a solvent for a TS from a TSguess

---

autode/__init__.py
doc/changelog.rst
tests/__init__.py

- Update testing
- Bumps version and changelog

Test fixture

---

autode/transition_states/ts_guess.py
tests/test_ts/test_ts_guess.py

Inherit solvent in TS guess from_species

---

.github/pull_request_template.md
.github/workflows/catch.yml
.github/workflows/pytest.yml
.github/workflows/pytest_cov.yml

To speed up PR checks if only documentation is being updated
***

Ignore doc paths for code CI

---

autode/values.py
doc/changelog.rst
tests/test_value.py

Fix units for values div mul

---

autode/hessians.py
autode/units.py
autode/values.py
doc/changelog.rst
tests/test_hessian.py
tests/test_value.py
tests/test_values.py

Remove hessian conversion on normal mode calculation

---

autode/wrappers/QChem.py
doc/changelog.rst
tests/test_wrappers/test_qchem.py

Hopefully this is correct!
***

Fix QChem not using max_core

---

autode/bracket/base.py
autode/bracket/dhs.py
doc/changelog.rst
tests/test_bracket/test_dhs.py

- Fix DHSGS large step sizes
- Only print TS guess if method converged
***

Fix DHSGS large step size bug

---

.github/workflows/pytest.yml
.github/workflows/pytest_cov.yml
autode/bracket/imagepair.py
autode/opt/coordinates/cartesian.py
autode/opt/coordinates/dic.py
autode/opt/coordinates/internals.py
autode/opt/coordinates/primitives.py
autode/opt/optimisers/base.py
autode/opt/optimisers/crfo.py
autode/opt/optimisers/prfo.py
autode/opt/optimisers/rfo.py
autode/opt/optimisers/trm.py
tests/test_opt/test_coordiantes.py
tests/test_opt/test_crfo.py

Refactor primitive coordinates and optimisers

---

autode/config.py
autode/wrappers/ORCA.py
doc/changelog.rst

Resolves https://github.com/duartegroup/autodE/discussions/322
***

Allow configurable ORCA output extensions

---

.github/workflows/catch.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/pytest.yml
.github/workflows/pytest_cov.yml
doc/changelog.rst
setup.py

Removes Python 3.8 support and updates some actions
***

remove py38 support

---

autode/species/molecule.py
doc/changelog.rst

allow srETKDGv3 in new RDKit

---

autode/conformers/conformers.py
doc/changelog.rst
tests/test_conformers.py

Also hit in the CI https://github.com/duartegroup/autodE/actions/runs/15466474752/job/43540313113
***

allow conformer calc failure
