duartegroup/autodE

autode/mol_graphs.py
autode/utils.py
tests/test_graphs.py
tests/test_utils.py

signal.SIGALRM is not present on Windows, so switch to a decorator using multiprocessing instead. **Should** improve Windows compatibility

Remove signal termination for windows compatibility

---

.github/ISSUE_TEMPLATE/bug_report.md
autode/smiles/angles.py
autode/smiles/atom_types.py
autode/smiles/builder.py
autode/smiles/smiles.py
autode/utils.py
tests/test_atoms.py
tests/test_molecule.py
tests/test_smiles_builder.py
tests/test_species.py

Add an issue template
Fixes bug in SMILES builder where linear atoms within rings raised a ValueError
Adds fallback to previous minimisation build if builder fails

Linear atoms in metallocycles

---

.gitignore
autode/ext/CMakeLists.txt
autode/ext/README.md
autode/ext/ade_dihedrals.pyx
autode/ext/ade_ext.cpp
autode/ext/ade_rb_opt.pyx
autode/ext/include/points.h
autode/ext/src/optimisers.cpp
autode/ext/src/points.cpp
autode/ext/tests/test_global_dihedral_min.cpp
autode/ext/tests/test_main.cpp
autode/ext/tests/test_point_gen.cpp
tests/test_xtb_calc.py

Sampling randomly from the dihedral space randomly is almost certainly less efficient than sampling more evenly, this PR adds an initial set of points well distributed

Improved stochastic sampling

---

autode/utils.py
doc/changelog.rst
tests/test_utils.py

Allows for multiprocessing 'start_method' to be defined outside of autodE. Required when calling, for example PyJulia. A minimal example is:
```python
import multiprocessing as mp
import autode as ade
mp.set_start_method("spawn", force=True)
def mol():
return ade.Molecule(atoms=[ade.Atom('H'), ade.Atom('H', x=0.7)])
if __name__ == '__main__':
with mp.Pool(2) as pool:
res = [pool.apply_async(mol) for _ in range(2)]
mols = [r.get() for r in res]
```
which gets stuck in an infinite loop. This PR adds a try-except block for setting and then skips calling functions with a timeout. If anyone knows how to keep both that would be great..
**NOTE**: As far as I'm aware the set_spawn method cannot be captured by codecov, but there is a test checking that it works.
---

Allow for multiprocessing spawn

---

autode/calculation.py
autode/species/species.py
autode/transition_states/base.py
doc/changelog.rst
tests/test_calculation.py
tests/test_gaussian_calc.py
tests/test_mopac_calc.py
tests/test_orca_calc.py
tests/test_xtb_calc.py

Fixes #84 by throwing a `CouldNotGetProperty` exception if an energy cannot be extracted from a completed calculation. Also adds a decorator for `Calculation` methods that require at least the name of the output filename to be set and hint that `run()` might have been forgotten to be called.

Modify Calculation get_energy

---

autode/atoms.py
autode/transition_states/locate_tss.py
autode/wrappers/base.py
autode/wrappers/keywords.py
doc/changelog.rst
tests/test_atoms.py
tests/test_methods.py

This PR allows for low-level adaptive path calculations to be skipped if there is no low-level electronic structure method to use and so the low-level=high-level. Potentially enabling a 2x speedup for TSs that cannot be found.

Improve TS guess functions

---

autode/wrappers/ORCA.py
tests/test_orca_calc.py

This PR adds a `_get_version_no_output` method to the ORCA wrapper, which in turn enables checking if the vdw charge scheme needs to be turned off when running analytical Hessian calculations. Unfortunately, this cannot be tested in CI 😕

Adds ORCA version extraction

---

autode/wrappers/MOPAC.py

Fixes a bug found while investigating #114 where the maximum number of optimisation cycles in the input keywords was not considered thus an extraneous number was added to the input, causing MOPAC2016 to crash with constrained optimisations. This PR fixes this by skipping any MaxOptCycles keywords in the input
***

MOPAC input fix 🐞 

---

autode/config.py
autode/reactions/reaction.py

Adds a configuration flag to enable free energy profiles when association complexes are also calculated – not sensible so off by default but available for those that are feeling brave. Suggested by Thijs – thanks for the suggestion 😄

Allow G profiles with association complexes

---

autode/units.py
autode/utils.py
autode/values.py
tests/test_calculation.py

This PR adds a check that sufficient physical memory is available before running a calculation. Requested in the _autodE_ tutorial session – thanks for the suggestion 😄

Check for sufficient available memory

---

autode/__init__.py
autode/calculation.py
autode/utils.py
autode/wrappers/XTB.py
doc/changelog.rst
setup.py
tests/test_utils.py

Fixes #132 
Context: Redirecting stdout generated from XTB calculations on Mac OS 12 can result in missed output.
This PR sets `GFORTRAN_UNBUFFERED_ALL=1` as a temporary environment variable while executing XTB, which seems to fix the problem (suggested in https://github.com/duartegroup/autodE/issues/132#issuecomment-1073656157). Unfortunately, without appropriate hardware/OS on GH runners this can't be tested, but locally it seems to work.
@matthewtoholland I'd appreciate if you could pull this branch and see if it fixes it for you too – thanks 👌

Fix for missed output redirection

---

autode/atoms.py
autode/calculation.py
autode/conformers/conformer.py
autode/conformers/conformers.py
autode/mol_graphs.py
autode/smiles/base.py
autode/smiles/builder.py
autode/smiles/parser.py
autode/smiles/smiles.py
autode/species/molecule.py
autode/species/species.py
autode/transition_states/base.py
autode/utils.py
autode/wrappers/XTB.py
doc/changelog.rst
doc/examples/reactions.rst
tests/test_atoms.py
tests/test_bond_rearrangement.py
tests/test_conformers.py
tests/test_graphs.py
tests/test_molecule.py
tests/test_reaction_class.py
tests/test_smiles_parser.py
tests/test_species.py

Closes #138 
Allows for atom classes to be defined in a SMILES string as per §3.1.7 of the openSMILES [spec](http://opensmiles.org/opensmiles.html). This allows TSs for identity reactions to be determined, where different atom classes are defined. For example
```python
import autode as ade
r = ade.Reaction('[Br-:1].C[Br:2]>>C[Br:1].[Br-:2]', solvent_name='water')
r.calculate_reaction_profile()
```
should work.
*** 
TODO:

Adds atom classes

---

autode/species/species.py
autode/thermochemistry/symmetry.py
doc/changelog.rst
tests/test_species.py
tests/test_thermochem.py

Thermochemistry calculation exception

---

README.md
autode/utils.py
tests/test_utils.py

If a function wrapped with `@utils.work_in` or `@utils.work_in_tmp_dir` throws an exception that is later caught, the working directory will be in the wrong location.
Note: `@utils.work_in` may have an unintended side-effect (unaffected by this PR). If an empty directory is passed to `@utils.work_in`, and nothing is produced in that directory, the directory will be deleted.

Exits working directory if wrapped function throws an exception.

---

autode/__init__.py
autode/species/molecule.py
doc/changelog.rst
setup.py
tests/test_molecule.py

Adds a warning if the SMILES-calculated multiplicity doesn't match a non-default specified value and an exception if the charge doesn't match. Suggest using different behaviour between spin multiplicity and charge due to – I think – the former not being able to be specified in a SMILES string

Add checking for incompatible charge/mult

---

autode/__init__.py
autode/transition_states/templates.py
doc/changelog.rst
setup.py
tests/test_config.py

Improve exception for invalid ts template folder path

---

.pre-commit-config.yaml
autode/__init__.py
autode/transition_states/base.py
autode/transition_states/transition_state.py
doc/changelog.rst
tests/test_ts/test_ts_template.py

Add `from_species` TS constructor

---

autode/calculations/executors.py

Note: with the example in #223 there is now no exception thrown, but I don't think any files are actually deleted 😕

Fix cleanup with null filename

---

autode/log/log.py
doc/changelog.rst
doc/config.rst
doc/reference/log.rst
tests/test_log.py

AutodE did not previously recognise the ERROR level of logging if set by "export AUTODE_LOG_LEVEL=ERROR".
***

Add "ERROR" level to logging

---

tests/conftest.py
tests/test_calculation.py
tests/test_conf_gen.py
tests/test_methods.py
tests/test_plotting.py
tests/test_utils.py

This was surprisingly easy – thought there would be more places where the Config was modified and then needed to be put back. Seems to work as intended
***

Autouse temp config context manager

---

autode/wrappers/XTB.py
doc/changelog.rst
tests/test_wrappers/test_xtb.py

Fixes cartesian coordinate constraints in XTB optimisations. I'm not convinced this ever worked correctly!
***

Fix xtb opt with cartesian coordinates

---

autode/opt/optimisers/rfo.py
doc/changelog.rst

Hessian is updated in RFO, as Hessian is used for step instead of augmented Hessian
***

Fix RFO hessian update bug

---

tests/test_utils.py
tests/testutils.py

The decorator `@requires_with_working_xtb_install` would previously always return on Windows since the `.exe` extension is returned by shutil. This PR fixes that bug.
(I didn't update the changelog because this should be covered under making autodE run on windows, I just didn't notice the issue in the previous PR)
***

Fix tests that use xTB on Windows

---

autode/config.py
autode/wrappers/XTB.py
doc/changelog.rst
tests/test_wrappers/test_xtb.py

Adds options to change the xTB `--etemp` and `--gfn` flags from Config. Default values (None) prevent use of those flags.
***

Add option to change xTB parameterisation version and temperature

---

autode/conformers/conformers.py
tests/test_conformers.py

Raises a more helpful exception in e.g #268 
-  Is this behaviour intuitive? Certainly useful for debugging but are there circumstances where you'd want to call `prune` and allow an empty result?

Raise exception if prune returns no conformers

---

autode/bracket/base.py
autode/bracket/dhs.py
autode/bracket/imagepair.py
autode/utils.py
tests/test_bracket/test_dhs.py
tests/test_bracket/test_imagepair.py

- Changes trust radius for optimiser to 0.1 Angstrom (since default step size for DHS is also 0.1 angstrom, anything larger does not make sense)
- Replaces `left_coord` and `right_coord` properties of the image pair object with `left_coords` and `right_coords` to match with other parts of autodE.
***

DHS code improvements

---

autode/config.py
autode/thermochemistry/igm.py
doc/changelog.rst
doc/install.rst
tests/test_thermochem.py

Adds the suggested method and tidies up the `igm` module. There's much more that could be better but 🤷🏼, at least it's better than it was.
***

Minenkov thermochem

---

autode/neb/original.py

Remove parallelisation from IDPP. The overhead from creating new processes is larger than any gains from parallelisation.
Test for diels-alder with 200 IDPP images
- MacOS - with parallelisation = 4.621 s, without parallelisation = 2.403 s
- Windows - with parallelisation = 10.26 s, without parallelisation = 2.331 s
***

Faster IDPP

---

README.md
autode/neb/original.py
autode/path/path.py
autode/pes/pes_nd.py
doc/changelog.rst
tests/test_import.py

We've been looking at the import time of the mlptrain package, which takes over a second on the cluster, and around 620ms on my dev machine with NVMe drive. Importing `autode` by itself takes 465 ms on main branch.
One of the easy wins is to import `matplotlib` only when needed, which saves around 160 ms.
Other potential improvements would come from delayed import of scipy and / or RDkit. But those would require more changes --- happy to open a separate PR if that is desired.
Corresponding PR on `mlptrain` repo: https://github.com/duartegroup/mlp-train/pull/84

Speedup package import time

---

.github/workflows/pytest_cov.yml
autode/transition_states/base.py
doc/changelog.rst
tests/test_ts/test_mode_checking.py

Thanks for catching this @shoubhikraj – very not ideal
***

fix no solvent

---

README.md
autode/input_output.py
doc/changelog.rst
tests/test_input_output.py

Added explicit space to print xyz coordinates to account for occasional cases where there is no space printed between two numbers, for example, `H    13.56100 -35.93700-100.99000`, and thus the printed xyz file becomes invalid.
```
########################################################################
[ERROR] Program stopped due to fatal error
-2- reading geometry input 'test2_sp_xtb.xyz' failed
-1- Error: Could not parse coordinates from xyz file
--> test2_sp_xtb.xyz:24:15-33
|
24 | H    13.56100 -35.93700-100.99000
|               ^^^^^^^^^^^^^^^^^^^ expected real value
|
########################################################################
```
***

Fix error in "atoms_to_xyz_file()" in "input_output.py"

---

autode/bracket/dhs.py
autode/bracket/imagepair.py
autode/opt/optimisers/utils.py
doc/changelog.rst
tests/test_bracket/test_dhs.py
tests/test_opt/test_opt_utils.py

(1) Uses multiple step sizes depending on the distance thresholds
(2) Replaces only gradient based peak detection to cubic polynomial based peak detection (both energies and gradients)
***

DHS variable step size

---

autode/atoms.py
autode/hessians.py
autode/values.py
doc/changelog.rst
tests/test_atoms.py
tests/test_bracket/test_dhs.py
tests/test_values.py

fix compatibility with numpy v2.0

---

autode/opt/coordinates/base.py
autode/opt/coordinates/cartesian.py
autode/opt/coordinates/dic.py
autode/opt/coordinates/primitives.py
autode/opt/optimisers/crfo.py
autode/opt/optimisers/qa.py
autode/opt/optimisers/rfo.py
autode/opt/optimisers/trm.py
doc/changelog.rst
tests/test_opt/test_coordiantes.py
tests/test_opt/test_crfo.py
tests/test_opt/test_opt.py
tests/test_opt/test_qa.py

(1) Adds a linear combination of bonds as a primitive
(2) Trust radius quasi-Newton optimiser
***

Add combination of bonds primitive and trust radius optimiser

---

autode/opt/coordinates/dic.py
autode/opt/coordinates/internals.py
doc/changelog.rst
tests/test_opt/test_coordiantes.py
tests/test_opt/test_crfo.py
tests/test_opt/test_qa.py

Improve DIC to Cartesian transformation

---

.github/scripts/install_xtb_ci.sh

Temporary fix for https://github.com/duartegroup/autodE/actions/runs/14955056856/job/42009591011 until there's an upstream xtb fix
***
* n/a Changelog has been updated

pin libgfortran to 14 in CI
